language: cpp

os:
  - linux
dist: trusty
sudo: required

compiler:
  - gcc

before_install: |
  sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  sudo apt-get update -qq
  sudo apt-get install -qq \
    g++-4.9 \
    libstdc++-4.9-dev \
    libpthread-stubs0-dev \
    libboost1.55-all-dev
  if [ "$CXX" = "g++" ]; then
    export CXX="g++-4.9" CC="gcc-4.9"
  fi

before_script: ./waf configure
script: ./waf test
