language: cpp
compiler: gcc
os: linux
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libstdc++-6-dev
      - libpthread-stubs0-dev
      - protobuf-compiler
      - libprotobuf-dev

# cache:
#   directories:
#     - boost_1_62_0

before_install:
  - wget 'https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz'
  - tar -xzf 'boost_1_62_0.tar.gz'
  - pushd 'boost_1_62_0'
  - export CC=gcc-6
  - ./bootstrap.sh
  - travis_wait 20 sudo ./b2 toolset=gcc-6 link=shared threading=multi runtime-link=shared -d0 install
  - popd

before_script: export CC=gcc-6 && export CXX=g++-6 && ./waf configure

script: export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" && ./waf test
